title: IA para Todos
description: IA prática para quem não é técnico
baseurl: "/ia-para-todos-blog"
url: "https://hermespontes.github.io"
theme: minima
lang: pt-BR
markdown: kramdown
plugins:
  - jekyll-feed
